import java.io.FileInputStream
import java.security.MessageDigest

plugins {
    id("com.android.application")
}

val userReleaseKeystore = rootProject.file("release.keystore")
val fallbackReleaseKeystore = layout.buildDirectory.file("keystore/auto-release.keystore").get().asFile
val usingUserReleaseKeystore = userReleaseKeystore.exists()
val releaseStorePassword = if (usingUserReleaseKeystore) {
    System.getenv("STORE_PASS") ?: "password"
} else {
    "android"
}
val releaseKeyAlias = if (usingUserReleaseKeystore) {
    System.getenv("KEY_ALIAS") ?: "release"
} else {
    "autogenerated-release"
}
val releaseKeyPassword = if (usingUserReleaseKeystore) {
    System.getenv("KEY_PASS") ?: releaseStorePassword
} else {
    "android"
}
val releaseSigningKeystore = if (usingUserReleaseKeystore) userReleaseKeystore else fallbackReleaseKeystore

android {
    namespace = "dev.surma.parakeeb"
    compileSdk = 35

    defaultConfig {
        applicationId = "dev.surma.parakeeb"
        minSdk = 26
        targetSdk = 35
        versionCode = 15
        versionName = "0.1.14"
        ndk {
            abiFilters += "arm64-v8a"
        }
    }

    signingConfigs {
        create("release") {
            storeFile = releaseSigningKeystore
            storePassword = releaseStorePassword
            keyAlias = releaseKeyAlias
            keyPassword = releaseKeyPassword
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            signingConfig = signingConfigs.getByName("release")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    // Source sets — the Rust-built .so files land in jniLibs via cargo-ndk
    sourceSets {
        getByName("main") {
            jniLibs.srcDirs("src/main/jniLibs")
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = false          // extractNativeLibs=false (16KB safe)
            keepDebugSymbols += "**/*.so"
        }
    }

    // Play Asset Delivery: large model files go into a separate asset pack
    // so the base module stays under the 200 MB Play Store limit.
    assetPacks += listOf(":model_assets")
}

// For APK builds (assemble/install), asset packs are ignored by AGP so we
// must include the asset-pack assets as an extra source directory.  For
// bundle builds the asset pack module handles delivery and we must NOT add
// the directory here (would cause duplicate-resource errors).
val isBundle = gradle.startParameter.taskNames.any {
    it.contains("bundle", ignoreCase = true)
}
if (!isBundle) {
    android.sourceSets.getByName("main") {
        assets.srcDirs(
            "src/main/assets",
            rootProject.file("model_assets/src/main/assets")
        )
    }
}

val generateFallbackReleaseKeystore by tasks.registering {
    description = "Generate a fallback release keystore when release.keystore is not provided"
    group = "build"

    onlyIf { !userReleaseKeystore.exists() && !fallbackReleaseKeystore.exists() }

    doLast {
        fallbackReleaseKeystore.parentFile.mkdirs()
        exec {
            commandLine(
                "keytool", "-genkeypair", "-v",
                "-keystore", fallbackReleaseKeystore.absolutePath,
                "-storetype", "PKCS12",
                "-alias", releaseKeyAlias,
                "-keyalg", "RSA",
                "-keysize", "2048",
                "-validity", "10000",
                "-storepass", releaseStorePassword,
                "-keypass", releaseKeyPassword,
                "-dname", "CN=Offline Voice Input, OU=Dev, O=NoTune, L=Unknown, S=Unknown, C=US",
                "-noprompt"
            )
        }
        println("Generated fallback release keystore at ${fallbackReleaseKeystore.absolutePath}")
    }
}

dependencies {
    implementation("com.microsoft.onnxruntime:onnxruntime-android:1.22.0")
    implementation("androidx.security:security-crypto:1.1.0-alpha06")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.google.code.gson:gson:2.11.0")

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.mockito:mockito-core:5.12.0")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")
}

// Dedicated configuration to resolve the ORT AAR for the Rust build
val ortNative: Configuration by configurations.creating
dependencies {
    ortNative("com.microsoft.onnxruntime:onnxruntime-android:1.22.0")
}

// ---------------------------------------------------------------------------
// Task to extract ORT headers & native libs for Rust compilation
// ---------------------------------------------------------------------------

val extractOrt by tasks.registering(Copy::class) {
    description = "Extract ONNX Runtime AAR for Rust build"
    group = "build"

    from(ortNative.elements.map { fileCollection ->
        fileCollection.map { zipTree(it) }
    })
    into(layout.buildDirectory.dir("ort-extracted"))
}

// ---------------------------------------------------------------------------
// Rust / cargo-ndk build task
// ---------------------------------------------------------------------------

val cargoNdkBuild by tasks.registering(Exec::class) {
    description = "Build Rust native code via cargo-ndk"
    group = "build"

    dependsOn(extractOrt)

    workingDir = rootProject.projectDir   // Cargo.toml lives at project root

    // Detect NDK path from local.properties or env
    val ndkDir = project.findProperty("ndk.dir")?.toString()
        ?: System.getenv("ANDROID_NDK_HOME")
        ?: System.getenv("ANDROID_NDK")
        ?: android.ndkDirectory.absolutePath

    environment("ANDROID_NDK_HOME", ndkDir)

    val extractDir = layout.buildDirectory.dir("ort-extracted").get().asFile
    environment("ORT_LIB_LOCATION", File(extractDir, "jni/arm64-v8a").absolutePath)
    environment("ORT_INCLUDE_DIR", File(extractDir, "headers").absolutePath)

    val jniLibsDir = project.file("src/main/jniLibs")

    commandLine(
        "cargo", "ndk",
        "-t", "arm64-v8a",
        "-o", jniLibsDir.absolutePath,
        "build", "--release"
    )

    // Copy libc++_shared.so from NDK (needed because Rust links against it dynamically)
    doLast {
        val ndkPath = environment["ANDROID_NDK_HOME"] as String
        val osName = System.getProperty("os.name").lowercase()
        val hostPrefix = when {
            osName.contains("mac") -> "darwin"
            osName.contains("linux") -> "linux"
            osName.contains("windows") -> "windows"
            else -> throw GradleException("Unsupported host OS for NDK toolchain detection: $osName")
        }

        val prebuiltRoot = File(ndkPath, "toolchains/llvm/prebuilt")
        val hostToolchain = prebuiltRoot.listFiles()
            ?.firstOrNull { it.isDirectory && it.name.startsWith(hostPrefix) }
            ?: throw GradleException(
                "No NDK prebuilt toolchain for host '$hostPrefix' found in: ${prebuiltRoot.absolutePath}"
            )

        val libcpp = File(hostToolchain, "sysroot/usr/lib/aarch64-linux-android/libc++_shared.so")
        if (libcpp.exists()) {
            val destDir = File(jniLibsDir, "arm64-v8a")
            destDir.mkdirs()
            libcpp.copyTo(File(destDir, "libc++_shared.so"), overwrite = true)
            println("Copied libc++_shared.so from NDK (${hostToolchain.name})")
        } else {
            throw GradleException("libc++_shared.so not found in NDK at: ${libcpp.absolutePath}")
        }
    }

    outputs.dir(jniLibsDir)
}

// Wire keystore generation and cargo-ndk build into the Android build lifecycle
tasks.named("preBuild") {
    dependsOn(generateFallbackReleaseKeystore)
    dependsOn(cargoNdkBuild)
}

// ---------------------------------------------------------------------------
// Model asset download task
// ---------------------------------------------------------------------------

data class ModelFile(val name: String, val sha256: String)

// Small metadata files stay in app/src/main/assets (always in base module)
val appAssetFiles = listOf(
    ModelFile("config.json", ""),
    ModelFile("vocab.txt", ""),
)

// Large ONNX model files go into the model_assets asset pack so the base
// module stays under the Play Store 200 MB compressed-download limit.
val modelPackFiles = listOf(
    ModelFile("encoder-model.int8.onnx",
        "6139d2fa7e1b086097b277c7149725edbab89cc7c7ae64b23c741be4055aff09"),
    ModelFile("decoder_joint-model.int8.onnx",
        "eea7483ee3d1a30375daedc8ed83e3960c91b098812127a0d99d1c8977667a70"),
    ModelFile("nemo128.onnx",
        "a9fde1486ebfcc08f328d75ad4610c67835fea58c73ba57e3209a6f6cf019e9f"),
)

val huggingFaceRepo = "https://huggingface.co/istupakov/parakeet-tdt-0.6b-v3-onnx/resolve/main"

fun downloadToDir(assetsDir: File, files: List<ModelFile>) {
    assetsDir.mkdirs()
    files.forEach { model ->
        val destFile = File(assetsDir, model.name)
        if (destFile.exists() && model.sha256.isNotEmpty()) {
            val digest = MessageDigest.getInstance("SHA-256")
            FileInputStream(destFile).use { fis ->
                val buf = ByteArray(8192)
                var read: Int
                while (fis.read(buf).also { read = it } != -1) {
                    digest.update(buf, 0, read)
                }
            }
            val hash = digest.digest().joinToString("") { "%02x".format(it) }
            if (hash == model.sha256) {
                println("  ✓ ${model.name} already downloaded and verified")
                return@forEach
            } else {
                println("  ✗ ${model.name} checksum mismatch, re-downloading...")
                destFile.delete()
            }
        }

        if (!destFile.exists()) {
            println("  ↓ Downloading ${model.name}...")
            val downloadUrl = "$huggingFaceRepo/${model.name}?download=true"
            val proc = ProcessBuilder("curl", "-L", "-f", "-o", destFile.absolutePath, downloadUrl)
                .inheritIO()
                .start()
            val exitCode = proc.waitFor()
            if (exitCode != 0) {
                throw GradleException("Failed to download ${model.name} (curl exit code $exitCode)")
            }

            if (model.sha256.isNotEmpty()) {
                val digest = MessageDigest.getInstance("SHA-256")
                FileInputStream(destFile).use { fis ->
                    val buf = ByteArray(8192)
                    var read: Int
                    while (fis.read(buf).also { read = it } != -1) {
                        digest.update(buf, 0, read)
                    }
                }
                val hash = digest.digest().joinToString("") { "%02x".format(it) }
                if (hash != model.sha256) {
                    throw GradleException(
                        "Checksum verification failed for ${model.name}:\n" +
                        "  Expected: ${model.sha256}\n" +
                        "  Got:      $hash"
                    )
                }
                println("  ✓ ${model.name} verified")
            }
        }
    }
}

val downloadModels by tasks.registering {
    description = "Download HuggingFace Parakeet model assets"
    group = "build"

    // Small metadata -> app assets (base module)
    val appAssetsDir = project.file("src/main/assets/parakeet-tdt-0.6b-v3-int8")
    // Large ONNX models -> asset pack (separate install-time delivery)
    val packAssetsDir = rootProject.file("model_assets/src/main/assets/parakeet-tdt-0.6b-v3-int8")

    outputs.dir(appAssetsDir)
    outputs.dir(packAssetsDir)

    doLast {
        downloadToDir(appAssetsDir, appAssetFiles)
        downloadToDir(packAssetsDir, modelPackFiles)
    }
}

tasks.named("preBuild") {
    dependsOn(downloadModels)
}
